api_staking_list:
    path:       /api/staking/
    controller: App\Controller\StakingController::list
    methods:    GET|HEAD
api_staking_chain:
    path:       /api/staking/{chainId}
    controller: App\Controller\StakingController::list
    methods:    GET|HEAD
api_staking_detail:
    path:       /api/staking/detail/{id}
    controller: App\Controller\StakingController::detail
    methods:    GET|HEAD
api_transaction:
    path: /api/transaction/add/
    controller: App\Controller\TransactionController::add
    methods: POST|HEAD
api_get_transaction:
    path: /api/transaction/get/{wallet}
    controller: App\Controller\TransactionController::get
    methods: GET|HEAD